### PR TITLE
fix 32bit builds and PIC strangeness

### PR DESCRIPTION
**Pull request by rphillips**
This fixes some of the strangeness people have seen with torch builds with Luajit 2.1:

https://groups.google.com/forum/embed/?place=forum/torch7#!topic/torch7/ZAijgrWgZiA

```
Linking C executable luajit
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_BC_POW':
buildvm_x86.dasc:(.text+0x84b): undefined reference to `lj_wrap_pow'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_log':
buildvm_x86.dasc:(.text+0x269c): undefined reference to `lj_wrap_log'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_log10':
buildvm_x86.dasc:(.text+0x26cb): undefined reference to `lj_wrap_log10'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_exp':
buildvm_x86.dasc:(.text+0x26fa): undefined reference to `lj_wrap_exp'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_sin':
```

We also came across it within the Luvit project.

### CODE REVIEW

**Comment by rphillips** [comment]
Luv reference: https://github.com/luvit/luv/pull/216

**Comment by soumith** [comment]
woohoo! thanks. never understood or investigated that issue.

**Comment by rphillips** [comment]
I believe the capitalization tells gcc to compile only and not to assemble and link.
